Increment3
NetworkPy/mtrrun pull request #3
Opened 2022-10-25 17:52 UTC by NetworkPy

created get requests for getting information about metrics

2022-10-27 12:34 UTC, shmel1k commented on cmd/agent/main.go
> +	"github.com/mtrrun/internal/config"
Минорно(но лучше сделать, конечно): скорее всего, лучше отформатировать через `goimports`

Здесь импорты сразу же отсортируются по-другому: сперва будут системные, потом уже гитхабовские

2022-10-27 13:42 UTC, shmel1k requested changes

2022-10-27 13:42 UTC, shmel1k commented on cmd/agent/main.go
> +	pollTicker := time.NewTicker(time.Duration(c.PollInterval) * time.Second)
Минорно: как вариант, можно перенести пониже, после всех метрик. Тогда будет попроще и можно будет удалить LOOP

2022-10-27 13:42 UTC, shmel1k commented on cmd/agent/main.go
> +	time.Sleep(time.Second * 2)
Так лучше не делать. Это не самый надёжный способ проверить, что всё завершилось

Есть два варианта: https://go.dev/play/p/ixqczsPvzZT - через дополнительный канал
Второй -- через sync.WaitGroup

2022-10-27 13:42 UTC, shmel1k commented on cmd/agent/main.go
> +	time.Sleep(time.Second * 2)
Когда-то давно я писал вот такой код:
https://github.com/city-mobil/gobuns/blob/master/graceful/graceful.go#L71

2022-10-27 13:42 UTC, shmel1k commented on internal/agent/agent.go
> +			break LOOP
Можно просто `return`

2022-10-27 13:42 UTC, shmel1k commented on internal/agent/agent.go
> +
Лишние отступы

2022-10-27 13:42 UTC, shmel1k commented on internal/agent/client.go
> +		return ErrNotStatusOK
Вот здесь лучше проеврить, что вообще за статус? В таких случаях можно создавать типизированные ошибки типа

```
type MyVeryOwnError struct {
    Message string
    Status int
}

func (m *MyVeryOwnError) Error()  string {
    return "some message"
}

// somewhere else

err := DoRequest()
if err != nil {
    if v, ok := err.(*MyVeryOwnError); ok {
        // some stuff
    }
}
```

2022-10-27 13:42 UTC, shmel1k commented on internal/agent/client.go
> +		newClient.Timeout = time.Duration(timeout) * time.Second
Лучше таймаут сразу передавать как time.Duration

2022-10-27 13:42 UTC, shmel1k commented on internal/agent/client.go
> +func (c *client) DoRequest(method, url string, header map[string]string, body []byte) error {
минорно: headers -- их же много :)

или headerMap -- тоже можно)

2022-10-27 13:42 UTC, shmel1k commented on internal/agent/client.go
> +
Вкусовщина: лучше не делать отступы между вызовом функции и проверкой ошибки на нил. Так они выглядят, как одно целое, конечному челоевку проще читать

Например,https://github.com/ydb-platform/ydb-go-sdk/blob/master/internal/ratelimiter/client.go#L259

2022-10-27 13:42 UTC, shmel1k commented on internal/agent/client.go
> +	defer resp.Body.Close()
Если настраивать golangci-lint, то он тут же ругнётся на что-то типа "Return error is not checked"

В таком случае можно сделать как-то так:
```go
defer func() {
    _ = resp.Body.Close()
}()
```

2022-10-27 13:42 UTC, shmel1k commented on internal/agent/convertor.go
> +		return buf.Bytes(), nil
Можно попробовать чуть проще
```go
if len(str) == 0 {
    return nil, nil
}

var buf bytes.Buffer
...
```

2022-10-27 13:42 UTC, shmel1k commented on internal/agent/convertor.go
> +	buf := new(bytes.Buffer)
Можно не делать через new. Конкретно здесь нас не интересует указатель, который под bytes.Buffer, и тащить его куда-то вовне тоже не надо. Поэтому можно просто обойтись

```
var buf bytes.Buffer
```

2022-10-27 13:42 UTC, shmel1k commented on internal/agent/convertor.go
> +		}
Лучше убрать лишнюю пустую строку

2022-10-27 13:42 UTC, shmel1k commented on internal/agent/convertor.go
> +		err := binary.Write(buf, binary.LittleEndian, uint64(len(byteStr)))
А зачем в таком формате? Возможно, лучше написать все метрики через `\n`?

2022-10-27 13:42 UTC, shmel1k commented on internal/agent/convertor.go
> +func convertStrToByte(str []string) ([]byte, error) {
Это имя не в полной мере отражает то, что делает функция

StrToByte -- я бы ожидал, что там что-то типа "есть однобайтовая строка -- вот мне её как байт и вернут". Но тут не совсем то

2022-10-27 13:42 UTC, shmel1k commented on internal/agent/counter.go
> +	return c.d
Опасно возвращать указатель под мьютексом. Объясню, почему.

Например, есть следующий код
```go
c := &counter{
    d: &Description{
        Field: 1,
    }
}


go func() {
    for {
        d := c.Desc()
        d.Field++
    }
time.Sleep(time.Second)
}()

go func() {
    for {
        d := c.Desc()
        d.Field++
    }
time.Sleep(time.Second)
}
```

Этот код приведёт к рейсу, потому что будет обращение к тем данным, которые по указателю

Здесь два варианта: 1. Убрать указатель(и тогда должна возвращаться копия данных)
2. Копировать данные под мьютексом в момент обращения

2022-10-27 13:42 UTC, shmel1k commented on internal/agent/counter.go
> +		mu:  sync.RWMutex{},
Не обязательно

2022-10-27 13:42 UTC, shmel1k commented on internal/agent/gauge.go
> +	return g.d
Здесь такая же проблема, как и в файле выше

2022-10-28 09:38 UTC, NetworkPy commented on cmd/agent/main.go
> +	MetricAlloc       = "Alloc"
Если сделать это в main, где происходит инициализация, то при создании метрик придется кастить Metric к string. Это не очень красиво, наоборот, добавляет неудобств, но это можно сделать в пакете agent.

2022-10-28 11:41 UTC, NetworkPy commented on cmd/agent/main.go
> +	defaultPollInterval = 2
Поправил во всем коде время, убрал int, сделал сразу time.Duration

2022-10-28 11:41 UTC, NetworkPy commented on cmd/agent/main.go
> +		log.Fatalf(err.Error())
Подправил

2022-10-28 11:41 UTC, NetworkPy commented on cmd/agent/main.go
> +	}
Сделал, перевел в константы

2022-10-28 11:41 UTC, NetworkPy commented on cmd/agent/main.go
> +	"github.com/mtrrun/internal/config"
Исправил, включил goimports в Goland, был почему-то выключен, также включил gofmt и govet.

2022-10-28 11:41 UTC, NetworkPy commented on internal/agent/tracker.go
> +		mu:      sync.RWMutex{},
Сделал, исправил во всем коде

2022-10-28 11:41 UTC, NetworkPy commented on internal/agent/convertor.go
> +		err := binary.Write(buf, binary.LittleEndian, uint64(len(byteStr)))
Удалил данный функционал

2022-10-28 11:41 UTC, NetworkPy commented on internal/agent/convertor.go
> +func convertStrToByte(str []string) ([]byte, error) {
Удалил данный функционал

2022-10-28 11:42 UTC, NetworkPy commented on internal/agent/counter.go
> +	return c.d
Учел это момент, теперь возвращаю копию

2022-10-28 13:00 UTC, shmel1k requested changes

2022-10-29 12:10 UTC, shmel1k approved these changes

2022-10-29 12:10 UTC, shmel1k commented on internal/agent/agent.go
> +	contentTypeHeader  = "Content-Type"
minor: лучше `headerContentType`, потому что могут быть ещё `headerHost`, `headerEsheChtoto`

2022-10-29 12:10 UTC, shmel1k commented on internal/agent/gauge.go
> +	g.mu.Lock()
minor: RLock() должно хватить

2022-11-03 10:51 UTC, merged